#!/bin/bash

pip3 install deepspeech
pip3 install deepspeech-tflite
git submodule update --force --recursive --init --remote
chmod 777 deepspeech/DeepSpeech
cd deepspeech/DeepSpeech
wget -c -i ./modelUrls


cd ../..
